<?php
return array (
  'title' => '星座',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '白羊座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3362',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '金牛座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3363',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '双子座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3364',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '巨蟹座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3365',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '狮子座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3366',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '处女座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3367',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '天秤座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3368',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '天蝎座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3369',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '射手座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3370',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '摩羯座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3371',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '水瓶座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3372',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '双鱼座',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3373',
      'keyid' => '3361',
      'listorder' => '0',
      'description' => '十二星座选择',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>