<?php
return array (
  'title' => '民族',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '汉族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '蒙古族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3381',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '回族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3382',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '藏族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3383',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '维吾尔族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3384',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '苗族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3385',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '彝族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3386',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '壮族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3387',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '布依族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '朝鲜族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '满族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '侗族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3391',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '瑶族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '白族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '土家族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '哈尼族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3395',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '哈萨克族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '傣族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '黎族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3398',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '僳僳族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '佤族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3400',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '畲族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3401',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3402 => 
    array (
      'linkageid' => '3402',
      'name' => '高山族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3402',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '拉祜族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3403',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3404 => 
    array (
      'linkageid' => '3404',
      'name' => '水族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3404',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '东乡族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3405',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '纳西族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3406',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3407 => 
    array (
      'linkageid' => '3407',
      'name' => '景颇族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3407',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '柯尔克孜族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3408',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '土族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3409',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3410 => 
    array (
      'linkageid' => '3410',
      'name' => '达斡尔族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3410',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '仫佬族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3411',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3412 => 
    array (
      'linkageid' => '3412',
      'name' => '羌族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3412',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3413 => 
    array (
      'linkageid' => '3413',
      'name' => '布朗族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3413',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '撒拉族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3414',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '毛南族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3415',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3416 => 
    array (
      'linkageid' => '3416',
      'name' => '仡佬族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3416',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3417 => 
    array (
      'linkageid' => '3417',
      'name' => '锡伯族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3417',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3418 => 
    array (
      'linkageid' => '3418',
      'name' => '阿昌族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3418',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3419 => 
    array (
      'linkageid' => '3419',
      'name' => '普米族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3419',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3420 => 
    array (
      'linkageid' => '3420',
      'name' => '塔吉克族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3420',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3421 => 
    array (
      'linkageid' => '3421',
      'name' => '怒族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3421',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3422 => 
    array (
      'linkageid' => '3422',
      'name' => '乌孜别克族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3422',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3423 => 
    array (
      'linkageid' => '3423',
      'name' => '俄罗斯族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3423',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3424 => 
    array (
      'linkageid' => '3424',
      'name' => '鄂温克族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3424',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3425 => 
    array (
      'linkageid' => '3425',
      'name' => '德昂族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3425',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3426 => 
    array (
      'linkageid' => '3426',
      'name' => '保安族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3426',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3427 => 
    array (
      'linkageid' => '3427',
      'name' => '裕固族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3427',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3428 => 
    array (
      'linkageid' => '3428',
      'name' => '京族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3428',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3429 => 
    array (
      'linkageid' => '3429',
      'name' => '塔塔尔族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3429',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3430 => 
    array (
      'linkageid' => '3430',
      'name' => '独龙族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3430',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3431 => 
    array (
      'linkageid' => '3431',
      'name' => '鄂伦春族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3431',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3432 => 
    array (
      'linkageid' => '3432',
      'name' => '赫哲族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3432',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3433 => 
    array (
      'linkageid' => '3433',
      'name' => '门巴族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3433',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3434 => 
    array (
      'linkageid' => '3434',
      'name' => '珞巴族',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3434',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3435 => 
    array (
      'linkageid' => '3435',
      'name' => '基诺族。',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3435',
      'keyid' => '3379',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>