<?php
return array (
  'title' => '国家',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3437 => 
    array (
      'linkageid' => '3437',
      'name' => '中国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3437',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3438 => 
    array (
      'linkageid' => '3438',
      'name' => '美国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3438',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3439 => 
    array (
      'linkageid' => '3439',
      'name' => '英国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3439',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3440 => 
    array (
      'linkageid' => '3440',
      'name' => '加拿大',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3440',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3441 => 
    array (
      'linkageid' => '3441',
      'name' => '法国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3441',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3442 => 
    array (
      'linkageid' => '3442',
      'name' => '新加坡',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3442',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3443 => 
    array (
      'linkageid' => '3443',
      'name' => '马来西亚',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3443',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3444 => 
    array (
      'linkageid' => '3444',
      'name' => '日本',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3444',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3445 => 
    array (
      'linkageid' => '3445',
      'name' => '韩国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3445',
      'keyid' => '3436',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>