<?php
return array (
  'title' => '唱片公司',
  'style' => '1',
  'siteid' => '0',
  'data' => 
  array (
    3450 => 
    array (
      'linkageid' => '3450',
      'name' => '华纳唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3450',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3451 => 
    array (
      'linkageid' => '3451',
      'name' => '环球唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3451',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3452 => 
    array (
      'linkageid' => '3452',
      'name' => 'Sony BMG',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3452',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3453 => 
    array (
      'linkageid' => '3453',
      'name' => '百代唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3453',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3454 => 
    array (
      'linkageid' => '3454',
      'name' => '未来无限文化',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3454',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3455 => 
    array (
      'linkageid' => '3455',
      'name' => '滚石唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3455',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3456 => 
    array (
      'linkageid' => '3456',
      'name' => '网络秀',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3456',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3457 => 
    array (
      'linkageid' => '3457',
      'name' => '钛友文化',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3457',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3458 => 
    array (
      'linkageid' => '3458',
      'name' => '太合麦田',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3458',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3459 => 
    array (
      'linkageid' => '3459',
      'name' => '星外星唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3459',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3460 => 
    array (
      'linkageid' => '3460',
      'name' => '华数唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3460',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3461 => 
    array (
      'linkageid' => '3461',
      'name' => '中国唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3461',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3462 => 
    array (
      'linkageid' => '3462',
      'name' => '易石大橙',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3462',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3463 => 
    array (
      'linkageid' => '3463',
      'name' => '嚎叫唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3463',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3464 => 
    array (
      'linkageid' => '3464',
      'name' => '美卡音像',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3464',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3465 => 
    array (
      'linkageid' => '3465',
      'name' => '灯火文化',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3465',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3466 => 
    array (
      'linkageid' => '3466',
      'name' => '摩登天空',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3466',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3467 => 
    array (
      'linkageid' => '3467',
      'name' => '保利演艺',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3467',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3468 => 
    array (
      'linkageid' => '3468',
      'name' => '天堂文化 麦丁国际',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3468',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3469 => 
    array (
      'linkageid' => '3469',
      'name' => '东方红音乐',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3469',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3470 => 
    array (
      'linkageid' => '3470',
      'name' => '大国文化',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3470',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3471 => 
    array (
      'linkageid' => '3471',
      'name' => '吉他中国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3471',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3472 => 
    array (
      'linkageid' => '3472',
      'name' => '飞蝶音乐',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3472',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3473 => 
    array (
      'linkageid' => '3473',
      'name' => 'EQ唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3473',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3474 => 
    array (
      'linkageid' => '3474',
      'name' => '艾迴音乐 乐海盛世',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3474',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3475 => 
    array (
      'linkageid' => '3475',
      'name' => '海蝶音乐',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3475',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3476 => 
    array (
      'linkageid' => '3476',
      'name' => '种子音乐',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3476',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3477 => 
    array (
      'linkageid' => '3477',
      'name' => '星娱音乐',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3477',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3478 => 
    array (
      'linkageid' => '3478',
      'name' => '亚神音乐',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3478',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3479 => 
    array (
      'linkageid' => '3479',
      'name' => '吉神文化',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3479',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3480 => 
    array (
      'linkageid' => '3480',
      'name' => '英皇星艺',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3480',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3481 => 
    array (
      'linkageid' => '3481',
      'name' => '天凯唱片',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3481',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3482 => 
    array (
      'linkageid' => '3482',
      'name' => '瀛凯文化',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3482',
      'keyid' => '3449',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>