<?php
return array (
  10 => 
  array (
    'modelid' => '10',
    'siteid' => '1',
    'name' => '普通会员',
    'description' => '普通会员',
    'tablename' => 'member_detail',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  12 => 
  array (
    'modelid' => '12',
    'siteid' => '1',
    'name' => '歌手',
    'description' => '歌手',
    'tablename' => 'member_singer',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  23 => 
  array (
    'modelid' => '23',
    'siteid' => '1',
    'name' => '高校',
    'description' => '高校账号',
    'tablename' => 'member_height',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  24 => 
  array (
    'modelid' => '24',
    'siteid' => '1',
    'name' => '媒体',
    'description' => '媒体模型',
    'tablename' => 'member_media',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
  25 => 
  array (
    'modelid' => '25',
    'siteid' => '1',
    'name' => '专家',
    'description' => '会员专家模型',
    'tablename' => 'member_expert',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '2',
  ),
);
?>