<?php
return array (
  1 => 
  array (
    'modelid' => '1',
    'siteid' => '1',
    'name' => '文章模型',
    'description' => '',
    'tablename' => 'news',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  2 => 
  array (
    'modelid' => '2',
    'siteid' => '1',
    'name' => '下载模型',
    'description' => '',
    'tablename' => 'download',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_download',
    'list_template' => 'list_download',
    'show_template' => 'show_download',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  3 => 
  array (
    'modelid' => '3',
    'siteid' => '1',
    'name' => '图片模型',
    'description' => '',
    'tablename' => 'picture',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_picture',
    'list_template' => 'list_picture',
    'show_template' => 'show_picture',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  30 => 
  array (
    'modelid' => '30',
    'siteid' => '1',
    'name' => '月榜单',
    'description' => '月榜单',
    'tablename' => 'mounth',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => 'content_list_mounth',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  19 => 
  array (
    'modelid' => '19',
    'siteid' => '1',
    'name' => '歌曲模型',
    'description' => '歌曲',
    'tablename' => 'music',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => 'content_list_music',
    'member_add_template' => 'content_publish',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  20 => 
  array (
    'modelid' => '20',
    'siteid' => '1',
    'name' => '唱片公司',
    'description' => '',
    'tablename' => 'record_company',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  21 => 
  array (
    'modelid' => '21',
    'siteid' => '1',
    'name' => '歌手模型',
    'description' => '',
    'tablename' => 'singer',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show_picture',
    'js_template' => '',
    'admin_list_template' => 'content_list_singer',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  22 => 
  array (
    'modelid' => '22',
    'siteid' => '1',
    'name' => '专辑模型',
    'description' => '专辑模型',
    'tablename' => 'sp',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  26 => 
  array (
    'modelid' => '26',
    'siteid' => '1',
    'name' => '测试模型',
    'description' => '',
    'tablename' => 'test',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  27 => 
  array (
    'modelid' => '27',
    'siteid' => '1',
    'name' => '视频模型2',
    'description' => '华语视频模型',
    'tablename' => 'video2',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list_hy_video',
    'show_template' => 'show_new',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  28 => 
  array (
    'modelid' => '28',
    'siteid' => '1',
    'name' => '演唱会模型',
    'description' => '演唱会的信息',
    'tablename' => 'concert',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  29 => 
  array (
    'modelid' => '29',
    'siteid' => '1',
    'name' => '榜单',
    'description' => '',
    'tablename' => 'chart',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => 'content_list_chart',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  31 => 
  array (
    'modelid' => '31',
    'siteid' => '1',
    'name' => '广告',
    'description' => '',
    'tablename' => 'advert',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
);
?>